import "server-only";
export { getSessionContext, requireSession } from "./_internal/session";
export { requirePermission, hasPermission, permissionScopes } from "./_internal/rbac";
export { P } from "./permissions";
export { auth, handlers, signIn, signOut, oauthProviderIds } from "./_internal/auth";
export { resolvePalette, resolveAppearance, getTenantPalette, getTenantSettings, getBrandText, resolveBrandText } from "./_internal/services/tenant.service";
export type { AppearanceData } from "./_internal/services/tenant.service";
export { getDashboardStats } from "./_internal/services/dashboard.service";
export { getTenantLogo, resolveBrandingLogo, resolveBrandingTenantId } from "./_internal/services/logo.service";
export type { TenantLogo, BrandingLogo } from "./_internal/services/logo.service";
